swagger: '2.0'
info:
  description: >-
    As Operações Financeiras Digitais QRPague é uma solução que utiliza a tecnologia de QRCode e pode ser implementado entre instituições distintas, sendo elas financeiras ou não. Esta API fornece um conjunto de serviços de emissão, autorização e confirmação de operações financeiras que ocorrem online.
  version: 1.0.0
  title: Operações Digitais QRPague
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: dev@sicoob.com.br
host: <<api.dominio.com.br>>
basePath: /qrpague
schemes:
  - https
paths:
  '/operacao':
    post:
      tags:
        - Operações Financeiras Digitais
      summary: Endpoit para gerar um QRCode de operação financeira digital.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        que um cliente possa solicitar um QRCode para uma operação financeira digital através da instituição sacada.
      operationId: operacao-financeira-criar
      security:
        - OAuth2: []
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/cnpjInstituicao'
      responses:
        '200':
          description: Requisição realizada com sucesso
          schema:
            $ref: '#/definitions/OperacaoFinanceira'
        '400':
          description: Exceção de negócio
          schema:
            $ref: '#/definitions/ErroNegocio'
        '500':
          description: Erro interno no servidor
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  '/operacoes':
    get:
      tags:
        - Operações Financeiras Digitais
      summary: Endpoit para recuperar informações de operações financeiras digitais gerada através do QRPAGUE.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        devolver as informações complementares de uma operação financeira digital gerada através da solução QRPague pelo parâmetro uuid referente àquela operação.
      operationId: operacao-financeira-recuperar
      security:
        - OAuth2: []
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/cnpjInstituicao'
        - in: query
          name: cpfCnpjFavorecido
          description: Especificação do CPF ou CPNJ do favorecido das operações financeiras digitais.
          required: true
          type: integer
        - in: query
          name: paginaInicial
          description: Especificação de uma página inicial para consulta de operações financeiras digitais.
          type: integer
        - in: query
          name: tamanhoPagina
          description: Especificação de um tamanho de página para consulta de operações financeiras digitais.
          type: integer
        - in: query
          name: periodoInicio
          description: Data de início de período da emissão das operações financeiras digitais para filtragem.
          type: integer
        - in: query
          name: periodoFim
          description: Data final de período da emissão das operações financeiras digitais para filtragem.
          type: integer
      responses:
        '200':
          description: Requisição realizada com sucesso
          schema:
            $ref: '#/definitions/ConsultaOperacaoFinanceira'
        '400':
          description: Exceção de negócio
          schema:
            $ref: '#/definitions/ErroNegocio'
        '500':
          description: Erro interno no servidor
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  '/operacoes/{uuid}':
    get:
      tags:
        - Operações Financeiras Digitais
      summary: Endpoit para consultar informações de uma operação financeira digital gerada através do QRPAGUE.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        devolver conjunto de operações financeiras digitais geradas através da solução QRPague por parâmetros de filtragem.
      operationId: operacao-financeira-consultar
      security:
        - OAuth2: []
      produces:
        - application/json
      parameters:
        - in: path
          name: uuid
          description: Identificador único da operação financeira na instituição financeira que gerou o QRPague.
          required: true
          type: string
          pattern: >-
            ^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$
        - $ref: '#/parameters/cnpjInstituicao'
      responses:
        '200':
          description: Requisição realizada com sucesso
          schema:
            $ref: '#/definitions/OperacaoFinanceira'
        '400':
          description: Exceção de negócio
          schema:
            $ref: '#/definitions/ErroNegocio'
        '500':
          description: Erro interno no servidor
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
    put:
      tags:
        - Operações Financeiras Digitais
      summary: Endpoit para atualizar informações de uma operação financeira digital gerada através do QRPAGUE.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        atualizar as informações de uma operação financeira digital gerada através da solução QRPague pelo parâmetro uuid referente àquela operação.
      operationId: operacao-financeira-atualizar
      security:
        - OAuth2: []
      produces:
        - application/json
      parameters:
        - in: path
          name: uuid
          description: Identificador único da operação financeira na instituição financeira que gerou o QRPague.
          required: true
          type: string
          pattern: >-
            ^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$
        - in: body
          name: operacao-financeira
          required: true
          schema:
            $ref: '#/definitions/OperacaoFinanceiraPart'
        - $ref: '#/parameters/cnpjInstituicao'
      responses:
        '200':
          description: Requisição realizada com sucesso
          schema:
            $ref: '#/definitions/OperacaoFinanceira'
        '400':
          description: Exceção de negócio
          schema:
            $ref: '#/definitions/ErroNegocio'
        '500':
          description: Erro interno no servidor
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: application
    tokenUrl: 'https://example.com/oauth/token'
    scopes: {}
parameters:
  cnpjInstituicao:
    in: header
    name: cnpjInstituicao
    description: |-
      CNPJ Matriz da instituição finaneira que referente à operação financeira digital.
    type: number
    format: integer
    required: true
definitions:
  ConsultaOperacaoFinanceira:
    type: object
    properties:
      quantidadeRegistros:
        type: integer
        description: >-
          Quantidade de objetos retornados em uma consulta de operações financeiras.
      links:
        type: array
        description: >-
          Links de possíveis ações a serem realiazadas do resultado vindo de uma consulta de operações financeiras.
        items:
          type: object
          properties:
            url:
              type: string
              description: >-
                Código do produto ou serviço para o cliente do QRCode emitido.
              example: <<api.dominio.com.br>>/qrpague/operacoes?paginaInicial=2&tamanhoPagina=20
            descricao:
              type: string
              description: >-
                Descricao do link.
              example: próxima pagina
            metodoHttp:
              type: string
              enum: [POST, GET, PUT, DELETE]
              description: >-
                Método http aplicado à URL espeficidas.
              example: GET
      resultados:
        type: array
        description: >-
          Conjunto de operações financeiras digitais recuperadas a partir dos parâmetros de filtragem informados.
        items:
          $ref: '#/definitions/OperacaoFinanceira'
  OperacaoFinanceira:
    type: object
    properties:
      versao:
        type: number
        format: float
        description: >-
          Número da versão do formato do JSON especificado.
        example: 1.0
      cnpjInstituicao:
         $ref: '#/parameters/cnpjInstituicao'
      uuid:
        type: string
        pattern: >-
          ^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$
        description: >-
          Identificador único da operação financeira digital na instituição sacadora. RFC 4122
        example: '3d0ca315-aff9–4fc2-be61–3b76b9a2d798'
      valor:
        type: integer
        description: >-
          Valor da operação financeira realizada, onde os últimos 2 dígitos são as cadas decimais.
        example: 150000
      descricao:
        type: string
        description: >-
          Descrição da operação financeira realizada.
        example: 'Pagamento do serviço de Advocacia na Meu escritório de advogados.'
      dataHoraSolicitacao:
        type: string
        format: date-time
        description: >-
          Data e hora da solicitação da operação financeira na instituição financeira. Formato RFC 3339, seção 5.6.
        example: '2017-07-21T17:32:28Z'
      dataHoraVencimento:
        type: string
        format: date-time
        description: >-
          Data e hora de vencimento da operação financeira na instituição financeira. Formato RFC 3339, seção 5.6.
        example: '2017-07-21T17:32:28Z'
      dataHoraEfetivacao:
        type: string
        format: date-time
        description: >-
          Data e hora de efetivacao da operação financeira na instituição financeira. Formato RFC 3339, seção 5.6.
        example: '2017-07-21T17:32:28Z'
      tipoOperacao:
        type: string
        enum: ["SAQUE", "TRANSFERÊNCIA", "PAGAMENTO"]
        description: >-
          Tipo da operação financeira digital realizada.
        example: 'PAGAMENTO'
      situacao:
        type: string
        enum: ["EMITIDO", "PAGO", "CANCELADO"]
        description: >-
          Situação da operação financeira digital realizada.
        example: 'PAGO'
      terminal:
        $ref: '#/definitions/Terminal'
      terminalEfetivacao:
        $ref: '#/definitions/Terminal'
      favorecido:
        type: object
        properties:
          nome:
            type: string
            description: >-
              Nome do favorecido na operação financeira digital.
            example: 'Meu escritório de advogados'
          cpfCnpj:
            description: >-
              Numero do CPF ou CNPJ do Favorecido da operação financeira digital (incluindo digito verificador, sem separador)
            type: string
            minLength: 11
            maxLength: 14
            example: '12345678999'
          instituicao:
            type: string
            description: >-
              ISQN da instituição do favorecido na operação financeira digital.
            example: '12345678999'
      itens: 
        type: array
        items:
          type: object
          properties:
            descricao48:
              type: string
              description: >-
                Descrição do produto para impressora de 48 posições.
            descricaoCompleta:
              type: string
              description: >-
                Descrição completa do produto ou serviço consumido.
            codigo:
              type: string
              description: >-
                Código do produto ou serviço para o cliente do QRCode emitido.
            quantidade:
              type: integer
              description: >-
                Quantaide de itens do produto ou serviço integrante da operação financeira digital.
            valorunitario:
              type: integer
              description: >-
                Valor unitário do produto ou serviço integrante da operação financeira digital.
            desconto:
              type: integer
              description: >-
                Desconto aplicado ao total do valor da operação financeira digital referente aos seus itens.
            total:
              type: integer
              description: >-
                Total do valor dos itens participantes da operação financeira digital referente do QRCode gerado.
            urlthumbimg:
              type: string
              description: >-
                URL da imagem do item participante da operação financeira digital referente do QRCode gerado.
        description: >-
          Itens participantes de uma da operação financeira digital gerado para um QRCode.
    required:
      - versao
      - cnpjInstituicao
      - uuid
      - valor
      - dataHoraSolicitacao
      - situacao
      - tipoOperacao
      - terminal
      - favorecido
  Terminal:
    type: object
    properties:
      idTerminal:
        type: string
        description: >-
          Identificador único do terminal na rede da instituição financeira.
        example: 0001128322332
      descricao:
        type: string
        description: >-
          Descrição do terminal na rede da instituição financeira.
        example: 0001128322332
      uf:
        type: string
        pattern: '^[A-Z]{2}$'
        description: >-
          Sigla da Unidade Federativa do terminal onde o saque está sendo
          solicitado.
        example: DF
      cep:
        type: string
        pattern: '^[0-9]{5}-[0-9]{3}$'
        description: >-
          CEP do endereço do terminal onde está sendo solicitado o saque.
        example: 70000-000
      latitudeTerminal:
        type: number
        format: double
        description: >-
          Latitude em graus do terminal onde está sendo solicitado o saque.
        example: '-15.7801'
      longitudeTerminal:
        type: number
        format: double
        description: >-
          Longitude em graus do terminal onde está sendo solicitado o saque.
        example: '-47.9292'
  OperacaoFinanceiraPart:
    type: object
    properties:
      dataHoraEfetivacao:
        type: string
        format: date-time
        description: >-
          Data e hora de efetivacao da operação financeira na instituição financeira. Formato RFC 3339, seção 5.6.
        example: '2017-07-21T17:32:28Z'
      situacao:
        type: string
        enum: ["EMITIDO", "PAGO", "CANCELADO"]
        description: >-
          Situação da operação financeira digital realizada.
        example: 'PAGO'
      terminalEfetivacao:
        $ref: '#/definitions/Terminal'
  ErroNegocio:
    type: object
    properties:
      codigoErro:
        type: number
        format: integer
        description: Código de erro de negócio.
        example: 1
      mensagemErro:
        type: string
        description: Mensagem de erro de negócio.
        example: QRCode inválido.
      dataReferencia:
        description: 'Data hora de referência da transação no formato RFC 3339, seção 5.6.'
        type: string
        format: date-time
        example: '2017-07-21T17:32:28Z'
    required:
      - codigoErro
      - mensagemErro
  OKNegocio:
    type: object
    properties:
      dataReferencia:
        description: 'Data hora de referência da transação no formato RFC 3339, seção 5.6.'
        type: string
        format: date-time
        example: '2017-07-21T17:32:28Z'
